### ISSUE TITLE
Async-await question

### ISSUE THREAD

**Issue by alexeychikk** [chfoo/thenshim#4]
I ran across these libraries which utilize macros to allow async-await syntax.
https://github.com/haxetink/tink_await
https://github.com/haxe-continuation/haxe-continuation

Is there any way to make your library work with one of those? Maybe you've done something similar?

**Comment by chfoo** [comment]
Unfortunately, I don't think it's possible without significant work. Based on my experience using async-await in Rust, it's very painful and messy to have async-await implemented by libraries instead of in the compiler. Each framework/library has their own way of doing things which aren't compatible. To make things work, there needs an agreement on a standard interface for async objects and the ability to swap async engines between frameworks.
